version: '3.8'
services:
  backend:
    build:
      context: ../puppeteer-render
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5050:5050
    # docker compose -p pup up -d 
